/** Pixel Putt (venue `pixel-putt`): the deterministic mini-golf sim, its seeded 9-hole courses and a search bot. */
export { PUTT, PUTT_SCORE_BASE, PUTT_SIM_VERSION } from "./tuning.js";
export {
  buildHole,
  cellIndex,
  cellKey,
  cellOf,
  generateCourse,
  inRect,
  mirrorSpec,
  motionOffset,
  templateSpec,
  TEMPLATE_COUNT,
  wave,
  type PuttBumper,
  type PuttCourse,
  type PuttHole,
  type PuttHoleSpec,
  type PuttMotion,
  type PuttMover,
  type PuttNib,
  type PuttPad,
  type PuttPoint,
  type PuttRail,
  type PuttRect,
  type PuttSlope,
  type PuttTier,
  type PuttWindmill,
} from "./course.js";
export {
  bladeAngle,
  createPuttSim,
  launchVelocity,
  puttScore,
  replayPutt,
  type BallMode,
  type PuttBounceKind,
  type PuttConfig,
  type PuttEvent,
  type PuttPhase,
  type PuttPreviewPoint,
  type PuttShotOutcome,
  type PuttSim,
  type PuttSummary,
  type PuttView,
} from "./sim.js";
export { chooseShot, type PuttBotOptions, type PuttBotShot } from "./bot.js";
